// <auto-generated />
using System;
using BUS_TICKIT_BOOKING_API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BUS_TICKIT_BOOKING_API.Migrations
{
    [DbContext(typeof(BusDBContext))]
    [Migration("20240202053818_nariya")]
    partial class nariya
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BUS_TICKIT_BOOKING_API.Model.BUS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("B_Booking_DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("B_Dropingpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("B_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("B_No")
                        .HasColumnType("integer");

                    b.Property<string>("B_Pickuppoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("P_Age")
                        .HasColumnType("integer");

                    b.Property<string>("P_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P_Xender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Set_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("bustickitbooking");
                });
#pragma warning restore 612, 618
        }
    }
}
