// <auto-generated />
using System;
using BUS_TICKIT_BOOKING_API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BUS_TICKIT_BOOKING_API.Migrations
{
    [DbContext(typeof(BusDBContext))]
    partial class BusDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BUS_TICKIT_BOOKING_API.Model.BUS", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("b_Booking_DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("b_Dropingpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("b_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("b_No")
                        .HasColumnType("integer");

                    b.Property<string>("b_Pickuppoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("p_Age")
                        .HasColumnType("integer");

                    b.Property<string>("p_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("p_Xender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("price")
                        .HasColumnType("integer");

                    b.Property<string>("set_No")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("bustickitbooking");
                });
#pragma warning restore 612, 618
        }
    }
}
